### ISSUE TITLE
feature request: streaming using discord's edit message function

### ISSUE THREAD

**Issue by yesbroc** [chrisrude/oobabot#50] opened 2023-06-22 11:45 UTC

**Comment by jmoney7823956789378** [comment] 2023-06-22 11:53
Already implemented, though a little jank at times.

**Comment by yesbroc** [comment] 2023-06-22 12:30
how do i use it?

**Comment by jmoney7823956789378** [comment] 2023-06-22 12:48
`--stream-responses`
The same option is available within config.yml too.

**Comment by chrisrude** [comment] 2023-06-22 16:40
yup, let me know how it works for you!  The challenge with this approach is that Discord will rate-limit its api responses, so depending on how long your responses are and how fast they're generated, you'll see varying results.

Thanks @jmoney7823956789378 for the tech support! :)

**Comment by jmoney7823956789378** [comment] 2023-06-22 16:47
No problem! Always got some free time at work.
Do you think you'd be able to expose the "streaming rate" to be adjusted in the config?
I've noticed that if I'm running certain models that pass the streaming limit (~24t/s) it can cause errors or delays.

**Comment by chrisrude** [comment] 2023-06-22 17:14
Sure thing!  Added in https://github.com/chrisrude/oobabot/commit/bf23d741d60f1bcfae1c9b58afa90f017e7af61e

If you try it, please lmk what values you find useful.  I would like to have defaults that work well for most users.

**Comment by jmoney7823956789378** [comment] 2023-06-22 18:37
> Sure thing! Added in [bf23d74](https://github.com/chrisrude/oobabot/commit/bf23d741d60f1bcfae1c9b58afa90f017e7af61e)
> 
> If you try it, please lmk what values you find useful. I would like to have defaults that work well for most users.

Awesome stuff!
I've been messing with it a little, but it seems like it'll still cause some strange behavior with context if it errors out.
When it encounters the error below, it will completely ignore the message for further conversation.
Here's the most common error I get consistently. 
```
 Tewi says:

Cyber Forensics involves investigating digital devices or data to uncover evidence related to crimes or other incidents.

---TRUNCATED LENGTH---

Offensive cyber capabilities may be employed as part of a nation's military strategy, intelligence gathering efforts, or law enforcement operations.2023-06-22 18:27:53,819 ERROR Error: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/oobabot/discord_bot.py", line 382, in _send_text_response_in_channel
    last_sent_message = await self._render_streaming_response(
  File "/usr/local/lib/python3.9/dist-packages/oobabot/discord_bot.py", line 538, in _render_streaming_response
    await last_message.edit(
  File "/usr/local/lib/python3.9/dist-packages/discord/message.py", line 2178, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, params=params)
  File "/usr/local/lib/python3.9/dist-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In content: Must be 2000 or fewer in length.
```

This is probably because I have the `max_new_tokens` set to 500, causing way too many tokens to be resent back and forth for editing the message. 
I'm also seeing my oobabot server (lxc container on separate machine) just pausing mid generation. 
This is the raw receiving-end from oobaboga, using `--log-all-the-things`.
Not sure what the cause is with that, or if you're able to reproduce.

**Comment by chrisrude** [comment] 2023-06-23 16:23
Glad it worked!  I'll test out 0.7 and see how it works as a default setting.

> Also, for some reason when using stream_responses oobabot does not read the message as context for the next message.
Thanks for pointing this out!  I hadn't noticed this before.  I'll see if I can address it.

> Invalid Form Body In content: Must be 2000 or fewer in length.
Thanks for pointing this out as well; I hadn't seen this before as my responses tend to be shorter in length.  But it should be possible to split longer streaming responses across messages.

**Comment by obi-o-n-e** [comment] 2023-07-02 21:23
Can this be pushed trough to the "plugin" version 🙏

**Comment by chrisrude** [comment] 2023-07-02 22:13
Yup, working on it soon!  It's been a minute since the last release, and I have a lot of improvements that need to get out. :)

I'm not planning to give the speed limit itself a UI widget, but on release you'll be able to change it via the advanced yaml editor.

**Comment by jmoney7823956789378** [comment] 2023-07-07 19:16
> Yup, working on it soon! It's been a minute since the last release, and I have a lot of improvements that need to get out. :)
> 
> I'm not planning to give the speed limit itself a UI widget, but on release you'll be able to change it via the advanced yaml editor.

I'm still testing out your latest 0.2.0 changes, and I'm finding that using `stream-responses: True` still causes the messages to be omitted from chat history.
![1688757366_07_07](https://github.com/chrisrude/oobabot/assets/133553475/2f8cef8a-4229-4a39-a980-443d4f0cd6a3)

**Comment by chrisrude** [comment] 2023-07-08 01:13
Yup, I haven't fixed that part yet.  I split off bug 63 to help me keep track of it.  Going to close this for now.

**Closed by chrisrude** 2023-07-08 01:13 UTC
